createOrReplace

	ref table _Measures
		measure emp_count = DISTINCTCOUNT ( 'acr_data_all'[employee_id] )
			formatString: #,0
			isHidden

			changedProperty = FormatString

			changedProperty = IsHidden


